# Data preparation: 2022-01-01–2026-10-18

Prepare five datasets for a common interval, read the saved files, and inspect their first rows and summary statistics.

In [3]:
START_DATE = "2022-01-01"
END_DATE = "2026-10-18"
OUTPUT_DIR = f"data/raw/{START_DATE}_{END_DATE}"

In [9]:
import sys
from pathlib import Path

import pandas as pd

ROOT = Path.cwd().parent
sys.path.insert(0, str(ROOT))

## SMARD — Actual solar generation

In [10]:
from services.mcp.app.data_sources.smard import fetch_smard_solar_generation

_ = fetch_smard_solar_generation(START_DATE, END_DATE, OUTPUT_DIR, "smard.parquet")

In [11]:
smard = pd.read_parquet(ROOT / OUTPUT_DIR / "smard.parquet")
smard.head()

,target_solar_generation_mwh,timestamp_utc,target_solar_generation_mw
0,2.0,2022-01-01 00:00:00+00:00,2.0
1,2.0,2022-01-01 01:00:00+00:00,2.0
2,2.0,2022-01-01 02:00:00+00:00,2.0
3,2.0,2022-01-01 03:00:00+00:00,2.0
4,2.0,2022-01-01 04:00:00+00:00,2.0

In [13]:
smard.info()

<class 'pandas.DataFrame'>
RangeIndex: 42048 entries, 0 to 42047
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   target_solar_generation_mwh  42048 non-null  float64
 1   timestamp_utc                42048 non-null  datetime64[ms, UTC]
 2   target_solar_generation_mw   42048 non-null  float64
dtypes: datetime64[ms, UTC](1), float64(2)
memory usage: 985.6 KB

In [12]:
smard.describe()

       target_solar_generation_mwh  target_solar_generation_mw
count                 42048.000000                42048.000000
mean                   7798.051915                 7798.051915
std                   11880.520072                11880.520072
min                       0.000000                    0.000000
25%                       6.080000                    6.080000
50%                     309.155000                  309.155000
75%                   12590.000000                12590.000000
max                   58055.530000                58055.530000

## Open-Meteo — Historical weather forecasts

In [14]:
from services.mcp.app.data_sources.open_meteo import (
    fetch_open_meteo_historical_forecast_weather,
)

_ = fetch_open_meteo_historical_forecast_weather(
    START_DATE, END_DATE, OUTPUT_DIR, "weather.parquet"
)

In [15]:
weather = pd.read_parquet(ROOT / OUTPUT_DIR / "weather.parquet")
weather.head()

,shortwave_radiation,direct_radiation,diffuse_radiation,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,temperature_2m,precipitation,wind_speed_10m,timestamp_utc,location,latitude,longitude
0,0.0,0.0,0.0,100,100,89,0,11.1,0.1,21.2,2022-01-01 00:00:00+00:00,Hamburg,53.55,10.0
1,0.0,0.0,0.0,100,100,8,0,11.1,0.0,20.2,2022-01-01 01:00:00+00:00,Hamburg,53.55,10.0
2,0.0,0.0,0.0,100,100,13,92,10.9,0.0,19.2,2022-01-01 02:00:00+00:00,Hamburg,53.55,10.0
3,0.0,0.0,0.0,100,100,67,86,10.5,0.0,20.3,2022-01-01 03:00:00+00:00,Hamburg,53.55,10.0
4,0.0,0.0,0.0,100,100,0,100,10.3,0.0,20.5,2022-01-01 04:00:00+00:00,Hamburg,53.55,10.0

In [16]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 420480 entries, 0 to 420479
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   shortwave_radiation  420480 non-null  float64
 1   direct_radiation     420480 non-null  float64
 2   diffuse_radiation    420480 non-null  float64
 3   cloud_cover          420480 non-null  int64
 4   cloud_cover_low      420480 non-null  int64
 5   cloud_cover_mid      420480 non-null  int64
 6   cloud_cover_high     420480 non-null  int64
 7   temperature_2m       420480 non-null  float64
 8   precipitation        420480 non-null  float64
 9   wind_speed_10m       420480 non-null  float64
 10  timestamp_utc        420480 non-null  datetime64[us, UTC]
 11  location             420480 non-null  str
 12  latitude             420480 non-null  float64
 13  longitude            420480 non-null  float64
dtypes: datetime64[us, UTC](1), float64(8), int64(4), str(1)
memory usage: 48.0 MB

In [17]:
weather.describe()

,shortwave_radiation,direct_radiation,diffuse_radiation,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,temperature_2m,precipitation,wind_speed_10m,latitude,longitude
count,420480.000000,420480.000000,420480.000000,420480.000000,420480.000000,420480.000000,420480.000000,420480.000000,420480.000000,420480.000000,420480.000000,420480.000000
mean,134.634223,76.220363,58.411670,70.085797,37.921368,41.639638,38.887823,11.999330,0.088802,9.873922,50.976000,10.115000
std,209.213160,151.137093,79.962108,39.214213,40.817895,42.692078,44.842099,8.007174,0.477776,5.624672,1.708289,2.065249
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-11.100000,0.000000,0.000000,48.140000,6.960000
25%,0.000000,0.000000,0.000000,37.000000,0.000000,0.000000,0.000000,6.000000,0.000000,5.800000,49.450000,8.680000
50%,7.000000,0.000000,6.000000,96.000000,17.000000,26.000000,5.000000,11.800000,0.000000,8.900000,51.225000,9.865000
75%,204.000000,69.000000,104.000000,100.000000,82.000000,92.000000,100.000000,17.700000,0.000000,13.000000,52.390000,11.580000
max,937.000000,810.000000,450.000000,100.000000,100.000000,100.000000,100.000000,40.400000,58.100000,49.900000,53.550000,13.410000

## MaStR — Installed solar capacity

In [18]:
from services.mcp.app.data_sources.mastr import prepare_installed_pv_capacity

_ = prepare_installed_pv_capacity(
    START_DATE, END_DATE, OUTPUT_DIR, "mastr.parquet", snapshot_date=END_DATE
)

In [19]:
capacity = pd.read_parquet(ROOT / OUTPUT_DIR / "mastr.parquet")
capacity.head()

              timestamp_utc  installed_pv_capacity_mw
0 2022-01-01 00:00:00+00:00              54499.407232
1 2022-01-01 01:00:00+00:00              54499.407232
2 2022-01-01 02:00:00+00:00              54499.407232
3 2022-01-01 03:00:00+00:00              54499.407232
4 2022-01-01 04:00:00+00:00              54499.407232

In [20]:
capacity.info()

<class 'pandas.DataFrame'>
RangeIndex: 42048 entries, 0 to 42047
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   timestamp_utc             42048 non-null  datetime64[us, UTC]
 1   installed_pv_capacity_mw  42048 non-null  float64
dtypes: datetime64[us, UTC](1), float64(1)
memory usage: 657.1 KB

In [21]:
capacity.describe()

       installed_pv_capacity_mw
count              42048.000000
mean               81877.461865
std                18989.856939
min                54499.407232
25%                63360.890157
50%                80357.707881
75%                98480.447895
max               116134.631935

## Calendar — Dates and holidays

In [22]:
from services.mcp.app.data_sources.calendar_features import (
    prepare_german_calendar_features,
)

_ = prepare_german_calendar_features(
    START_DATE, END_DATE, OUTPUT_DIR, "calendar.parquet"
)

In [23]:
calendar = pd.read_parquet(ROOT / OUTPUT_DIR / "calendar.parquet")
calendar.head()

,timestamp_utc,timestamp_local,date_local,hour_local,day_of_year,month,weekday,is_weekend,is_holiday_de,holiday_name_de,hour_sin,hour_cos,day_of_year_sin,day_of_year_cos
0,2022-01-01 00:00:00+00:00,2022-01-01 01:00:00+01:00,2022-01-01,1,1,1,5,1,1,New Year's Day,0.258819,0.965926,0.017202,0.999852
1,2022-01-01 01:00:00+00:00,2022-01-01 02:00:00+01:00,2022-01-01,2,1,1,5,1,1,New Year's Day,0.500000,0.866025,0.017202,0.999852
2,2022-01-01 02:00:00+00:00,2022-01-01 03:00:00+01:00,2022-01-01,3,1,1,5,1,1,New Year's Day,0.707107,0.707107,0.017202,0.999852
3,2022-01-01 03:00:00+00:00,2022-01-01 04:00:00+01:00,2022-01-01,4,1,1,5,1,1,New Year's Day,0.866025,0.500000,0.017202,0.999852
4,2022-01-01 04:00:00+00:00,2022-01-01 05:00:00+01:00,2022-01-01,5,1,1,5,1,1,New Year's Day,0.965926,0.258819,0.017202,0.999852

In [24]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 42048 entries, 0 to 42047
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp_utc    42048 non-null  datetime64[us, UTC]
 1   timestamp_local  42048 non-null  datetime64[us, Europe/Berlin]
 2   date_local       42048 non-null  object
 3   hour_local       42048 non-null  int32
 4   day_of_year      42048 non-null  int32
 5   month            42048 non-null  int32
 6   weekday          42048 non-null  int32
 7   is_weekend       42048 non-null  int64
 8   is_holiday_de    42048 non-null  int64
 9   holiday_name_de  1031 non-null   str
 10  hour_sin         42048 non-null  float64
 11  hour_cos         42048 non-null  float64
 12  day_of_year_sin  42048 non-null  float64
 13  day_of_year_cos  42048 non-null  float64
dtypes: datetime64[us, Europe/Berlin](1), datetime64[us, UTC](1), float64(4), int32(4), int64(2), object(1), str(1)
memory usage: 3.9+ MB

In [25]:
calendar.describe()

,hour_local,day_of_year,month,weekday,is_weekend,is_holiday_de,hour_sin,hour_cos,day_of_year_sin,day_of_year_cos
count,42048.000000,42048.000000,42048.000000,42048.000000,42048.000000,42048.000000,4.204800e+04,4.204800e+04,42048.000000,42048.000000
mean,11.499976,176.990986,6.325247,3.002592,0.286482,0.024520,-5.735848e-06,2.375866e-06,0.023061,-0.031936
std,6.922303,103.123345,3.375156,2.000765,0.452123,0.154658,7.071121e-01,7.071183e-01,0.710166,0.702948
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,-1.000000e+00,-1.000000e+00,-0.999999,-0.999979
25%,5.750000,88.000000,3.000000,1.000000,0.000000,0.000000,-7.071068e-01,-7.071068e-01,-0.691351,-0.731378
50%,11.500000,176.000000,6.000000,3.000000,0.000000,0.000000,6.123234e-17,-6.123234e-17,0.062318,-0.063391
75%,17.250000,263.000000,9.000000,5.000000,1.000000,0.000000,7.071068e-01,7.071068e-01,0.730644,0.665287
max,23.000000,366.000000,12.000000,6.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,0.999986,0.999991

## pvlib — Solar geometry and clear-sky radiation

In [26]:
from services.mcp.app.data_sources.solar_features import prepare_pvlib_solar_features

_ = prepare_pvlib_solar_features(START_DATE, END_DATE, OUTPUT_DIR, "solar.parquet")

In [27]:
solar = pd.read_parquet(ROOT / OUTPUT_DIR / "solar.parquet")
solar.head()

,timestamp_utc,solar_elevation_mean,solar_apparent_zenith_mean,clear_sky_ghi_mean,clear_sky_dni_mean,clear_sky_dhi_mean,solar_elevation_max,clear_sky_ghi_max,is_daylight_anywhere
0,2022-01-01 00:00:00+00:00,-61.089320,151.089320,0.0,0.0,0.0,-58.691395,0.0,0
1,2022-01-01 01:00:00+00:00,-56.271318,146.271318,0.0,0.0,0.0,-53.775136,0.0,0
2,2022-01-01 02:00:00+00:00,-48.766169,138.766169,0.0,0.0,0.0,-46.276662,0.0,0
3,2022-01-01 03:00:00+00:00,-39.930995,129.930995,0.0,0.0,0.0,-37.631142,0.0,0
4,2022-01-01 04:00:00+00:00,-30.576277,120.576277,0.0,0.0,0.0,-28.555138,0.0,0

In [28]:
solar.info()

<class 'pandas.DataFrame'>
RangeIndex: 42048 entries, 0 to 42047
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   timestamp_utc               42048 non-null  datetime64[us, UTC]
 1   solar_elevation_mean        42048 non-null  float64
 2   solar_apparent_zenith_mean  42048 non-null  float64
 3   clear_sky_ghi_mean          42048 non-null  float64
 4   clear_sky_dni_mean          42048 non-null  float64
 5   clear_sky_dhi_mean          42048 non-null  float64
 6   solar_elevation_max         42048 non-null  float64
 7   clear_sky_ghi_max           42048 non-null  float64
 8   is_daylight_anywhere        42048 non-null  int64
dtypes: datetime64[us, UTC](1), float64(7), int64(1)
memory usage: 2.9 MB

In [29]:
solar.describe()

,solar_elevation_mean,solar_apparent_zenith_mean,clear_sky_ghi_mean,clear_sky_dni_mean,clear_sky_dhi_mean,solar_elevation_max,clear_sky_ghi_max,is_daylight_anywhere
count,42048.000000,42048.000000,42048.000000,42048.000000,42048.000000,42048.000000,42048.000000,42048.000000
mean,1.052130,88.910318,181.846588,270.996288,40.762426,3.287558,201.837092,0.528848
std,30.378367,30.390384,254.992078,316.229389,50.523911,30.430600,271.554169,0.499173
min,-62.210275,27.883074,0.000000,0.000000,0.000000,-59.700115,0.000000,0.000000
25%,-21.096733,66.380066,0.000000,0.000000,0.000000,-19.010721,0.000000,0.000000
50%,1.034428,88.648555,2.771301,11.724756,2.047197,3.017794,8.733870,1.000000
75%,23.582373,111.096733,326.810148,622.635946,84.253401,25.859344,372.170255,1.000000
max,62.108166,152.210275,847.949089,807.106615,146.651090,65.109351,888.847914,1.000000